### ISSUE TITLE
Updates for 1.3

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RealSolarSystem#109]
With #108 PhineasFreak has fixed many of the updates to make RSS compatible with the new version of Kopernicus and 1.3.

These are some other things that, in my opinion, should be done to improve RSS overall. The first one is a game breaking save that will cause some issues with people playing in 1.2.2 or earlier versions, so it should be handled carefully. The others are just ideas from me, please let me know your opinions on them.

- [x] Move all textures (except Earth) into the /RSS-Textures/PluginData/ folder. One of the more recent additions of Kopernicus allows the textures, heightmaps and biome maps to be stored there so they are not loaded by KSP until needed. It saves a ton of memory.
- [x] Add Ceres and Vesta (artwork completed, config files are made for Half Size RSS, just need to be converted to full size)
- [x] Add the 5 largest moons of Uranus: Ariel, Miranda, Oberon, Titania, Umbriel (artwork completed, config files are made for Half Size RSS, just need to be converted to full size)
- [x] Update the Earth biome map to be accurate with the known biomes of the world: Shores (not real, but makes sense for KSP), Grasslands, Tundra, Mountains, Desert, Tropics, Ice Caps, Water, Taiga, Forest, Savanna, Chaparral (this map and correct config is already completed and can be used immediately)
http://i.imgur.com/NDd5QGL.png (Earth Biome Map)

- [x] New Moon Biomes - I have discussed this one before as I created a Moon Biome map that has many of different parts of the Moon named. I know that the balance of science has been the primary concern with not implementing something like this. I propose 4 options:
  - (1) We could just plug it in as it is and have greater science returns from visiting the Moon
  - (2) We could change the multiplier of the Moon science. Currently it is Landed x 4.5, Low Space x 3.5, High Space x 3.0. These could all be lowered by somewhere between 0.5 and 1 point to balance the science gains of the new biomes.
  - (3) If we are going to be implementing a new tech tree, we can take into account the greater science gains from visiting the Moon and adjust the new values accordingly.
  - (4) We keep the current Moon biomes
http://i.imgur.com/exXKbp3.jpg (Moon Biome Map)

Pinging for comment:
@NathanKell @stratochief66 @jwvanderbeck 
Anyone else that I missed?

**Comment by Sigma88** [comment]
if you want you can use [SD](https://github.com/Sigma88/Sigma-Dimensions) to scale the cfgs up to real size

you can then copy the mm cachefile and use the Body nodes included there

feel free to ping me if you have questions about how to use it

**Comment by PhineasFreak** [comment]
@pap1723 All of these are pretty easy to implement and would add a ton of value to RSS! Especially the new bodies and biome maps!

For the new bodies we also have the configs from RSS Expanded (the very first version - worked as a charm) if you want some extra help.

**Comment by leudaimon** [comment]
The Earth biomes have always bothered me, and a move towards realism would be nice. However, this would double the number of biomes and could create the same balance issues as the moon ones, just worse. Maybe it would be possible to clump some of them?

**Comment by pap1723** [comment]
@leudaimon you are not wrong, there are 12 biomes vs the 8 currently in RSS and that will change quite a bit, I agree. Chapparal could go, it is only found around the Mediterranean Sea. Savannah could probably be grouped into Grasslands, since that is similar. Those I would be good with, any others would be difficult in my mind, but am open to suggestions.

**Comment by Sigma88** [comment]
wouldn't it be easier to write a plugin that handles diminishing return on science?

if I understand this correctly the problem is the quantity of science that one could get from earth.

what if you set all biomes to produce a lot of science, but keep track of how much science is obtained from earth, and gradually diminish the amout you get from earth biome exploration.

this means you have enough science to kick start the space program, but you are then "forced" to look away from earth if you want to keep getting science

**Comment by NathanKell** [comment]
It's also a question of whack-a-mole--It's hard/tedious enough now to hit all the biomes, increasing their number increases that. Ah, RealScience... ^_^

**Comment by NathanKell** [comment]
(that's not to say we shouldn't change biomes of course, just that we should be mindful. And maybe a cap or diminishing returns makes sense as a way to thread the needle.)

**Comment by Sigma88** [comment]
that's the idea that always made the most sense to me, trying to balance the total science has to be a nightmare...

I don't know how feasible it would be to store information linked to a specific save, but if it's possible I'd say it's the best way to go.

I might even look into making it a customizeable plugin

**Comment by leudaimon** [comment]
@pap1723 I would clump chaparral into the savanas. It's very similar to the south american Cerrado, which is widely considered a savana. 
Another possibility is to clump tropics and forests, given what is being labeled as tropics is tropical forest, and the current forest is temperate forest. 

A more radical clumping would be: Grasslands (Grasslands and Tundra), Woodlands (Savanna and Chaparral), Forests (Tropics, Forest, Taiga), Water, Shore, Polar Caps, Desert. This would keep the numbers at 8, but with a more meaningful classification based on vegetation.

**Comment by leudaimon** [comment]
@pap1723 I would clump chaparral into the savanas. It's very similar to the south american Cerrado, which is widely considered a savana. 
Another possibility is to clump tropics and forests, given what is being labeled as tropics is tropical forest, and the current forest is temperate forest. 

A more radical clumping would be: Grasslands (Grasslands and Tundra), Woodlands (Savanna and Chaparral), Forests (Tropics, Forest, Taiga), Water, Shore, Polar Caps, Desert, Mountains. This would keep the numbers close, but with a more meaningful classification based on vegetation.

**Comment by Sigma88** [comment]
I had some time to fiddle with it, and I am confident I can make something work in the near future

here's an example of what it might look like:

![screenshot 2017-06-03 20 28 48](https://cloud.githubusercontent.com/assets/12640834/26756301/40a87012-489f-11e7-8278-d57306b84430.png)

**Comment by Sigma88** [comment]
I released a first attempt at limiting science,


[Forum Thread](http://forum.kerbalspaceprogram.com/index.php?/topic/161564-0/)


[GitHub Repo](https://github.com/Sigma88/Sigma-ScienceBalance)


for now it's just a simple hard cap, but it can be improved, just let me know if you have something specific in mind

**Comment by PhineasFreak** [comment]
First steps, hurray! @pap1723 is amazing!

**Comment by Clement-Cardot** [comment]
Hello everyone 
How many time do you need to update the mods to 1.3 ?
(I'm french so maybe there is mistakes ^^ )

**Comment by Bornholio** [comment]
Can someone generate a new .dll for the updates at current time.  I'd love to get to testing vs 1.3/Principia(чебышёв)/RSSVE RC4.  Sounded like we are at a good cutoff point concerning biomes and other facets.  I've tested it all vs principia(cayley) and RSSVE RC3 without issues so far (1.2.2).

**Comment by PhineasFreak** [comment]
@Bornholio Yep, here you go: https://github.com/PhineasFreak/DocBin/blob/master/DocBin/dll_files/RealSolarSystem.dll

**Unofficial** RSS assembly (for testing purposes **only**)

**Comment by Bornholio** [comment]
Yeah, Mercury was there, Oberon was not funky biomed, moon is a bit simpler biomed.  All looks good with minimal 1.3 install.   [album](http://imgur.com/a/2DItG)

Still having issue getting the weird colors to go away installing RSSVE, but it does work.

**Comment by PhineasFreak** [comment]
Hey @pap1723, are you still planning on adding Ceres and Vesta into the mix? I have been playing/testing with them for some time now and everything seems to be in order. The on demand texture loading is a nice feature to have but it can be currently mitigated by the x64 requirement of RSS.

BTW, did you also include an updated Mars SS texture? It looks much better now!

**Comment by eggrobin** [comment]
This has been done in #113 and in KSP-RO/RSS-Textures#16.
