### ISSUE TITLE
Moon min timewarpAltitudeLimits dip below the surface

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RealSolarSystem#111]
currently 10x timewarp is set to 5km, which is below the surface in many cases.  This causes you not to be able to land on the moon when using principia.  (see: https://github.com/mockingbirdnest/Principia/issues/1440, https://github.com/mockingbirdnest/Principia/issues/1346, https://github.com/mockingbirdnest/Principia/issues/1413)

Propose raising this to 15km.

**Comment by NathanKell** [comment]
I dislike not being able to warp down low, but it seems we need to do this, so we will do it.

**Comment by rsparkyc** [comment]
@NathanKell I agree, and it sounds like eventually it will be supported properly:
Egg said
> Eventually, we could support managing the vessel even when KSP is using a rotating frame, and that issue would disappear; this would also allow managing the vessel as soon as it leaves the ground even in an atmosphere, allowing use of our trajectory plots during ascent.

If that happens, we could go back and undo any changes we made to support this.

**Comment by NathanKell** [comment]
Ah, yes, in that magical day when the sectors unite and Checkpoint Charlie is out of a job!
(Vous sortez du secteur eggrobain)

@eggrobin do we also need to change the inverse rot alts?

**Comment by eggrobin** [comment]
No, the inverse rotation altitudes are fine, or rather, what happens is that they're way too high to start with, everywhere, especially with stock, which is why we lower them so that we start tracking the vessel as soon as possible. The issue mockingbirdnest/Principia#1413 is precisely that Principia forcefully lowers these altitudes to the timewarp altitude, working with the (mistaken) assumption that this will be above the surface. Changing the timewarp altitude is the workaround until the aforementioned reunification.

**Comment by NathanKell** [comment]
What if we set inverse rot to 5km and left warp where it is?

**Comment by NathanKell** [comment]
Sorry, 15km.

**Comment by eggrobin** [comment]
It is already set way above 5 km (in stock, 100 km for most bodies, and you don't appear to override that value), that's the issue, it's so high that we ended up dropping the vessel at absurdly high altitudes unless we reduced it. Therefore we always reduce it to the higher of the timewarp limit and the atmosphere; this works well enough if there is an atmosphere, not very well in airless stock worlds (highlands of minmus), and badly here.

**Comment by NathanKell** [comment]
Yeah, and doing that wouldn't help because it's a straight min() as you say. Ok!
