### ISSUE TITLE
Latest Kopernicus requires fixes to RSS in 1.3.1

### ISSUE THREAD

**Issue by Theysen** [KSP-RO/RealSolarSystem#127]
* latest released Kopernicus and I guess forthgoing versions rendered current RSS oceans invisible
* severe FPS drops and hickups

I didn't look into what exactly changed, just leaving a reminder.

**Comment by Bornholio** [comment]
Did some troubleshooting.  Kopernicus later than -3 version results in non functional oceans.

**Comment by PhineasFreak** [comment]
Note that all new bodies inherited by RSS Planets & Moons Expanded (Ceres, Vesta, Uranus moons) also require their textures to be updated (re-exported?), since they appear broken in-game (lighting glitches).

**Comment by Bornholio** [comment]
https://github.com/KSP-RO/RealSolarSystem/pull/130 worked to fix the oceans.

**Comment by PhineasFreak** [comment]
Closing this as both the oceans and the new RSS bodies have been fixed.
