### ISSUE TITLE
update kscswitcher for rss 1.3.1 ksp

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealSolarSystem#135]
Pinging you here @rsparkyc we need a kscswitcher release for 1.3.1 so we can release the updated RSS then RO. Also can push rights be added to RO org so the other maintainers of it can make releases in future in case we can't get in touch. Ferram/egg have been doing releases of other dependencies because the permissions are all over the place and even they can't access this.

**Comment by Olympic1** [comment]
or @NathanKell
