### ISSUE TITLE
permissions of all ro repos

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealSolarSystem#136]
@jwvanderbeck do you have permissions to change the RO organization permissions? 

I've been talking to @eggrobin about this and it seems that the permissions are all over the place. We agree that at the very least like rssdatetime, rss should be added to ro organization permissions. 

It would be beneficial to have all the hard dependencies here added to avoid the back and forth with missing members and maintainers and problems. Then we won't need to ask 5-10 different people who don't even maintain those repos to make releases because the owners are awol.

Or at the very least add new maintainers and remove some of the ones that are completely gone. There are some maintainers listed that make no sense and haven't been around/contactable in years.

**Comment by jwvanderbeck** [comment]
The way it seems to be set up right now is there is a "Core" team with admin privileges to most all of the repos.  That Core is just 3 people, @NathanKell , @pjf , and @stratochief66 

Then there is a specific team for each Repo with Write permissions.  So for example in RSS that team is named "Real Solar system", in TF it is named "TestFlight" and each of those teams has different membership.

I don't know any of the reasoning behind this setup as I don't recall ever discussing it with NK, but it seems clear the intent was to limit overall Org wide (KSP-RO) permissions to a very small group and then only open up specific repos as necessary based on the people who worked on them the most.

What I can do for now is add the "RealismOverhaul" team to all of the core mod repos, but a larger membership/permissions pass might be a good thing.  Are both NK and Stratochief absent now?

Can you provide me a list of core mod repos that need that team added?

**Comment by raidernick** [comment]
Why does pjf have permissions still exactly?

The core RSS/RO required repos(and most important) are: 
rsstimedate
RSS
RSS-Textures
RealHeat
Realplume
RP0
AJE
SolverEngines
Testflight
KSCswitcher

NK is absent and comes back occasionally, but once a year or two is not good enough for releases. We have decided we want a more frequent release schedule, especially for RO with the amount of config changes it goes through. As for strat, I heard from theysen that he had quit KSP/modding so I don't expect to see him again.

We don't need ALL people given permissions for these repos and the core ro membership seems fairly large(35 people?). But I would like at least myself, egg and ferram to have permissions.

Are you not one of the core people? You are listed at the same membership level from what I can see, the permissions should really be rejigged though.

**Comment by pap1723** [comment]
Pjf has access because he started RO and RP-0 with NK.

**Comment by raidernick** [comment]
I meant why does he still have access, because he hasn't been active on it for a few years, but it doesn't really matter I guess as long as the organization permissions I listed out above are dealt with.

**Comment by jwvanderbeck** [comment]
Mainly just because no one has bothered to go in and clean up permissions.  Besides, he might come back at some point, who knows.  I mean look at me? :)

I'll add the RealismOverhaul team to those repos assuming they are all under the KSP-RO organization.

**Comment by jwvanderbeck** [comment]
Ok for now I just added the RealismOverhaul team to all those.  Let me know if I missed any.  Could maybe do with a trimmed down list, but I'll worry about that later.

> Are you not one of the core people? You are listed at the same membership level from what I can see, the permissions should really be rejigged though.

I don't seem to be in the "Core" team, but since I am an owner on the org I pretty much have super privileges anyway so its irrelevant.

**Comment by raidernick** [comment]
@jwvanderbeck doesn't appear to have worked, I have no access to any of those still except rsstimedate.

**Comment by jwvanderbeck** [comment]
*sigh*  I added the teams but didn't set them to Write permission.  Can you confirm **this** repo is good now?  If so I can make the same change to the others.

**Comment by raidernick** [comment]
yep this one is all good

**Comment by jwvanderbeck** [comment]
ok, I think I got them all.  If I missed any I will catch them up in the morning.

**Comment by raidernick** [comment]
ok it seems to be working but I didn't check every repo just a few. What exactly did you change? Did you add the secret RO group as a subgroup in those repos for permissions? Or did you create a new group with them? I don't see myself in any new groups so I'm assuming you added the hidden RO group(the one with 11 people) to them correct?

**Comment by jwvanderbeck** [comment]
Yes.  Well I had added the group before but it defaults to only Read permission in each repo so I had to go back to each and change it to Write for that group in each.

**Comment by raidernick** [comment]
ok i'll check the rest tomorrow to make sure they all work. If all is good i'll close this issue. Thanks for doing this.

**Comment by eggrobin** [comment]
Thanks for quickly looking into this, @jwvanderbeck. At some point we will probably want to widen the set of maintainers as mentioned above, but I think for now this should unblock @raidernick's release effort.
