### ISSUE TITLE
Floating Tiles

### ISSUE THREAD

**Issue by EstrelaGaliza** [KSP-RO/RealSolarSystem#137]
![image](https://user-images.githubusercontent.com/37704589/38461471-0cfceaa2-3ad1-11e8-8932-e5264f3161d7.png)
Terrain tiles dissapear when reentry atmosphere from suborbital flight.
Always close to the launchpad (same on KSP and Baikonur)

Tried many clean installs and always appears.

I experienced the issue with a clean install (RSS, Textures, Kopernicus and Squad folder).

I tested all recommended Kopernicus versions for 1.3.1 and the problem is still there.

KSP version: 1.3.1
Kopernicus: 1.3.1-3/4/5/6/7
Scatterer: 0.0320b
RSSVE: 1.3.1-3
EVE: 1.2.2-1
-Master Real Solar Sistem
-pap1723/ScaledRSS-Textures

Thanks.

**Comment by Kerbas-ad-astra** [comment]
I can confirm this behavior, both in 1.3.1 (with or without #139) and in my tinkering with 1.4.2.  Fortunately, it seems that dropping debris below the capsule (e.g. a propulsion module) brings the terrain back when it collides.  Furthermore, it seems that orbital reentries should not be affected, since this only seems to affect the terrain directly under (for some radius) the point of reentry, and a vehicle coming back from orbit will fly well past it.

**Comment by EstrelaGaliza** [comment]
So technically would be possible space shuttle landings at runway?

**Comment by raidernick** [comment]
@PhineasFreak I know you said this was not an RSS bug, but I'm becoming concerned that we did make some kind of mistake somewhere. I am getting more bugs reports from people on the forum about this bug now, insisting it's impossible to replicate in 13.0 but only occurs in 13.1. I am inclined to agree, as personally I've NEVER seen this issue ever before, but now I am seeing it fairly often ingame.

http://jimbodiah.com/ksp/rss_terrain.jpg

**Comment by agustincaniglia** [comment]
Hey, Is there a fix already for KSP 1.3.1?
I mean... I tried a lot of things and it keeps going on. Further more, sometimes when the terrain does come back, it does being offset and gaps appeart between the terrain textures. I tried several things to get rid of this, with no luck. Please help.

**Comment by EstrelaGaliza** [comment]
Virtually solved thanks to Siimav.

Drop .dll

 into \GameData\RealSolarSystem\Plugins\

**Comment by EstrelaGaliza** [comment]
[rss.zip](https://github.com/KSP-RO/RealSolarSystem/files/2815398/rss.zip)
 Virtually solved thanks to Siimav

Drop the .dll  into \GameData\RealSolarSystem\Plugins\

**Comment by PhineasFreak** [comment]
Confirmed that **[the fix by @siimav](https://github.com/KSP-RO/RealSolarSystem/pull/159)** works perfectly and it will be part of the KSP 1.6.1 RSS release.

**Comment by PhineasFreak** [comment]
This has been fixed in the v16.0 release. Closing issue.

**Comment by rubynouille** [comment]
![20190515035459_1](https://user-images.githubusercontent.com/30053061/57748800-afbfaa80-76db-11e9-9d6c-0e7f2c3eff83.jpg)
![20190515035516_1](https://user-images.githubusercontent.com/30053061/57748802-afbfaa80-76db-11e9-90f9-0a5563a6fc18.jpg)

KSP version 1.7 with RSSVE v1.6.1 RC1 with Scatterer v0.0540 + EVE 1.4.2-2
It's still here, in suborbitals flights above ~150km and disappears beyond 300 I believe
Still always close to the launchpad
I end up in the water when launching from Cape Canaveral

#169
