### ISSUE TITLE
Terrain artifact issue revisit

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealSolarSystem#142]
@PhineasFreak I know you said this was not an RSS bug, but I'm becoming concerned that we did make some kind of mistake somewhere. I am getting more bugs reports from people on the forum about this bug now, insisting it's impossible to replicate in 13.0 but only occurs in 13.1. I am inclined to agree, as personally I've NEVER seen this issue ever before, but now I am seeing it fairly often ingame.

http://jimbodiah.com/ksp/rss_terrain.jpg

**Comment by PhineasFreak** [comment]
Fun fact: i was making some RO configs the other day (with the old texture pack installed) and i got them on my first vessel launch. I am inclined to disagree that this is specific to this update (Moon was not touched in any way, config or texture-side). But it is easy to check it by removing the updated normal maps completely.

I will become a PITA and also ping @stollD to chime in, as he knows how Kopernicus handles SS/PQS much better than me...

**Comment by raidernick** [comment]
Yep I know the moon wasn't touched that's why I'm confused. I asked the guy to replicate this using RSS 13.1 and RSS texture 13.0, so he won't have any normal maps and can rule out RSS as being the cause. I'm fairly certain it's NOT RSS but I'm not convinced it's not the textures.

**Comment by raidernick** [comment]
I have noticed though, that if you use things like hyperedit to put yourself into orbit around any body but earth, these artifacts pretty much ALWAYS show up. I've been able to then get rid of them by hyperediting back to the same spot two or three more times and then the artifacts seem to vanish. It seems to be something to do with how it's loading in the terrain yeah.

**Comment by PhineasFreak** [comment]
Worth also mentioning that the latest bug report on it was done with the previous texture pack. And Hyperedit has been repeatedly been identified as a cause for breaking bodies in both stock and modded solar systems.

Question: have you tried to move a vessel using the KSP "hyperedit" menu? It would be nice to compare these two and i assume that the KSP hyperedit will be good enough not to have these bugs.

**Comment by raidernick** [comment]
yes I have and actually the stock hyperedit doesn't have any problems. What I usually do is when I want to hyperedit something, I use the stock to teleport myself to that body first in a random orbit. Then I use hyperedit to fine tune exactly what I want. The stock one sucks at doing specific or precise things and is more difficult to use, but hyperedit causes all sorts of issues is you use it initially to transport somewhere, so I use both.
