### ISSUE TITLE
Ship's orbit line in map view

### ISSUE THREAD

**Issue by SkyKaptn** [KSP-RO/RealSolarSystem#143]
When zooming out in the map view the orbit line suddenly gets non-occlusion from the planet. Two images posted in the RSS forum thread:
https://forum.kerbalspaceprogram.com/index.php?/topic/173396-131-real-solar-system-v131-26-apr-2018/&do=findComment&comment=3412431

Navigating and orientation in the map view gets very confusing if there is more than one orbit around the planet.

RSS was installed with the listed dependencies in the forum OP, all dependencies was 1.3.1. 
Win10, i7 4790K, GTX1080

**Comment by PhineasFreak** [comment]
Yea, this is not an RSS issue. RSS **exposes** it but in the end it is either a stock KSP bug or a Kopernicus limitation regarding the near/far orbital line rendering depth.
