### ISSUE TITLE
Elevations on Earth about 3x too high.

### ISSUE THREAD

**Issue by Nightside101010** [KSP-RO/RealSolarSystem#149]
Elevations on Earth are very exaggerated. For example Mt. Rainier in game is 11,300 m the actual one in Washington State, US is closer to 4400 m. 
Does anyone know if there is a reason for this (ie game play, making the terrain look more dramatic)? I'm trying to work on a fix locally so I would be interested in the background information.

Site Visit Report:
![screenshot42](https://user-images.githubusercontent.com/20480557/46642123-3b5fd000-cb2a-11e8-84ad-0b14cd64beaa.png)

Thanks

**Comment by pap1723** [comment]
I believe that the real reason is the resolution of the map. It is very,
very small in relation to the size of the world it is wrapped on.

**Comment by PhineasFreak** [comment]
Probably just the inaccuracy of the height map.  The"dynamic range" for the Earth terrain is ~20000 m, meaning a resolution of ~78 m per step (height map is stored in .dds L8 format). So, we are not limited by the format, only by the supplied data.

**Comment by Nightside101010** [comment]
I think you are both right. I wouldn't be suprised if the high and low ends got "mushed" a bit in reformatting making the range between Marianas and Everest some unknown value besides 20 km.
I had a little trouble locating source data that wasn't 100s of GB, but I eventually found a few relief maps showing. I will experiment and see if I can improve the map. 
Does anyone have advice about which .dds format is best for KSP?

**Comment by PhineasFreak** [comment]
You would have to use the already existing format. Memo:

* .dds DXT 1 for color map textures
* .dds DXT 5 for normal map textures
* .dds L8 (preferred) or .png grayscale (fallback) for height map textures
* .png RGBA for biome map textures

**Comment by Growflavor** [comment]
> I will experiment and see if I can improve the map.

I would be grateful for any tips, obstacles, etc you encountered as I am also interested in how to work with, make & calibrate height maps, as I would like to improve them for myself for many of the RSS moons (& if successful, would be happy to share them).  Thanks!

<details><summary>Unity HeightMaps</summary><p>

## (https://docs.unity3d.com/Manual/terrain-Heightmaps.html)

"Terrain tools that affect height, such as Raise or Lower Terrain and Set Height, use a grayscale texture called a__ heightmap__. Unity represents the height of each point on the Terrain as a value in a rectangular array. It represents this array using a grayscale heightmap. Heightmaps are built into the Terrain, and the values stored in a heightmap define the height of each point or vertex on the Terrain."

& refference **not** a shader heightmap
https://docs.unity3d.com/Manual/StandardShaderMaterialParameterHeightMap.html 

</p></details>

**Comment by Growflavor** [comment]
> * .dds DXT 1 for color map textures
> * .dds DXT 5 for normal map textures
> * .dds L8 (preferred) or .png grayscale (fallback) for height map textures
> * .png RGBA for biome map textures

Are these all saved without MIP maps?

Also, are any of the many other options (e.g. shown in the screenshot at the link below) relevant to making the above types of textures for KSP?

https://i.imgur.com/zPXIwbW.png

Thanks for the insights! :-)

**Comment by RCrockford** [comment]
This should be fixed by #198.

**Comment by raidernick** [comment]
I can confirm that it is fixed now
