### ISSUE TITLE
Ice Giant atmospheres

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealSolarSystem#16]
Neptune and Uranus don't have atmospheres. That's bad. Anyone have any data on them?

**Comment by stratochief66** [comment]
Ouch, good catch. Can we scale the values used for Saturn or Jupiter as a filler until more accurate corrections can be made?

**Comment by stratochief66** [comment]
Wiki has a few tables for Uranus, but I am unable to access the scientific sources they site:
http://upload.wikimedia.org/wikipedia/commons/6/63/Uranian_stratosphere.png
http://upload.wikimedia.org/wikipedia/commons/4/45/Tropospheric_profile_Uranus_new.svg

**Comment by pjf** [comment]
Just to clarify, you're looking for pressure curves, temperature curves, atmospheric composition, any of the above?

**Comment by NathanKell** [comment]
@stratochief66 cool! That should be enough to make some curves that'd work for both ice giants.

@pjf hah good catch. We need to set gamma and molar mass for Mars and Venus and Titan, too. Oops.
We need:
Ratio of specific heats
molar mass
pressure curve
temperature curve
(per the other issue) any seasonal, latitudinal, or diurnal variation in temperature

**Comment by pap1723** [comment]
Has this been figured out? If not, I will contact OhioBob from the KSP forums as he is the resident expert on atmospheres and has helped me with Quarter RSS and Half RSS

**Comment by NathanKell** [comment]
OhioBob redid the atmospheres about 8 months ago. We're all good!
