### ISSUE TITLE
Launch pad Flag twitching

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealSolarSystem#164]
In both 1.4.5 and 1.6.1 RSS causes the flag near the launch pad to flip out. It glitches and twitches all over. It's extremely distracting and never did this previously. I don't know what changed that could be causing this but I would love to see it fixed.
@PhineasFreak

**Comment by PhineasFreak** [comment]
No idea why this happens but i will take a look.

**Comment by Nightside101010** [comment]
As I recall, this also occurred when I used Sigma dimensions to rescale an
earth sized Kerbin.

**Comment by PhineasFreak** [comment]
Also tested a 10x stock KSP rescale and i can confirm the findings. This is either an issue with Kopernicus (common between Sigma rescales and RSS "rescales") or just another "runway" (Squad breaking things).

**Comment by raidernick** [comment]
@PhineasFreak It's not a kopernicus issue on it's own, using just kopernicus by itself the flag is fine. I also opened an issue there and they won't do anything if kopernicus works in pure stock by itself which it does.

**Comment by siimav** [comment]
Fixed in the Kopernicus release for KSP 1.8
