### ISSUE TITLE
[Discussion] RSS package dependencies

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealSolarSystem#165]
Currently RSS distributes ModuleManager and Kopernicus (and MFI by extension) as part of the official releases. Should these continue be part of the release packages or separate them as external dependencies?

**Pros:**

* Less overall maintenance required (no need to upload new versions of the dependencies in the repository).
* Less worries about distributing old versions of mods (in the case newer versions are available).

**Cons:**

* Users must install the correct versions by themselves (only if installing manually).
* Users might forget that they need them, leading to a situation similar to the "RSS Textures".

Thoughts?

**Edit:** there is also the fact that RSS could get rid of the version checker in the future (KSP releases do not tend to break stuff as they previously did and none of the RSS source code parts actually required any major bugfixing between KSP 1.0 and now, when the entire RSS project was ported to Kopernicus). So, RSS may not need to have "hard" updates between KSP versions, only when bug fixes/new features are introduced (for example the KSP 1.6 RSS release would work just fine under KSP 1.4 and 1.5, sans the Compatibility Checker locks).

**Comment by siimav** [comment]
I'd prefer to keep these mods as external dependencies. I think the biggest advantage of that approach is that updating RSS itself is no longer needed in case a new release for Kopernicus is made available with some useful bugfixes.

**Comment by MikeOnTea** [comment]
Same

**Comment by whale2** [comment]
External dependencies are fine to me, but I have a side note on version compatibility.
The fact that versions between 1.4 - 1.6 are inter-compatible does not actually guarantee that any future version will be compatible as well and blindly pulling any new version of dependencies could eventually break stuff.

**Comment by pap1723** [comment]
Completely agree about making them external

**Comment by PhineasFreak** [comment]
Closing this as the latest release (v16.0) does not include the above dependencies. Thank you everyone for chiming in!
