### ISSUE TITLE
Compatibility warning with KSP 1.6.1

### ISSUE THREAD

**Issue by joaocosta-azores** [KSP-RO/RealSolarSystem#166]
Hello,

I did get this warning when installing add-on.
Is there any issue with this KSP version, or can I ignore the warning?
![Screenshot 2019-04-06 at 10 46 33](https://user-images.githubusercontent.com/2188826/55668422-cc093580-5859-11e9-80e3-faf0908574ee.png)

After that, when I get to main menu, all I see is a black screen with the icon loading at the bottom right corner. I can hear the sound gaming but loading doesn't finish.
![Screenshot 2019-04-06 at 10 53 06](https://user-images.githubusercontent.com/2188826/55668477-5a7db700-585a-11e9-8639-3009bca7e464.png)

**Comment by leudaimon** [comment]
Well, RSS is not compatible with 1.6.1, latest release is for 1.4.5.

**Comment by raidernick** [comment]
Why is this even posted? RSS is not updated for 1.6.1 so this is not a real bug...
