### ISSUE TITLE
(still) floating tiles in 1.7

### ISSUE THREAD

**Issue by rubynouille** [KSP-RO/RealSolarSystem#169]
![20190515035516_1](https://user-images.githubusercontent.com/30053061/57748760-87d04700-76db-11e9-84f2-a761678bb9cd.jpg)
![20190515035459_1](https://user-images.githubusercontent.com/30053061/57748761-87d04700-76db-11e9-9729-d874ed65af13.jpg)

KSP version 1.7 with RSSVE v1.6.1 RC1 with Scatterer v0.0540 + EVE 1.4.2-2
It's still here, in suborbitals flights above ~150km and disappears beyond 300 I believe
Still always close to the launchpad
I end up in the water when launching from Cape Canaveral

(I know 1.7 isn't officially compatible but it seems to work besides that)

#137

**Comment by siimav** [comment]
No, there aren't any floating tiles in in RSS. The only issue is that you installed it on 1.7 whereas the max supported version is currently 1.6.1. Please wait until the official release or just take into consideration that everything might not be working as it should.
