### ISSUE TITLE
Moon's Position for Apollo 11

### ISSUE THREAD

**Issue by tylerraiz** [KSP-RO/RealSolarSystem#172]
In an attempt to recreate Apollo 11, I found that doing the TLI burn at the correct time (around 16:22 UTC on July 16th, 1969 given a launch at 13:32 to about the right Earth orbit) would not even come close to reaching the Moon (it's roughly opposite where it needs to be). Also on that day, the Moon's relative inclination at launch time is 18 degrees. Changing the orbital parameters using data from HORIZONS for 1969-01-01 and setting the Epoch and KAC clock accordingly did not help the inclination, though it did make the transfer burn at least possible. The inclination, even with what I can correct during launch, makes it difficult to get a free return. 

Edit: sorry, was writing this and testing the details when RaiderNick posted. He was aware of the trouble I was having.

**Comment by PhineasFreak** [comment]
If you really want to do historical recreations then you **must** use Principia. You are not going to get the accuracy required from the stock KSP trajectory integrator.

**Comment by tylerraiz** [comment]
If I get the data from HORIZONS  for 1969 and reset the system to eliminate the effect of the integrator, the fact that the inclination is still so far off is probably an intrinsic problem. That said, I'm not fussed - I can get good enough conditions by launching on August 16th instead.
