### ISSUE TITLE
There is a bug in my RSS that the trajectory will not be blocked by the sphere

### ISSUE THREAD

**Issue by yixiangop** [KSP-RO/RealSolarSystem#178]
There is a bug in my RSS that the trajectory will not be blocked by the sphere
=

KSP version 1.7.3
RSS version v16.4
-

Gamedata directory:
-
* Kopernicus
* ModularFlightIntegrator
* RealSolarSystem
* RSS-Textures
* Squad
* SquadExpansion
* ModuleManager.4.0.3.dll

Performance in the game
-
![image](https://user-images.githubusercontent.com/51064238/70377526-6c1adf80-1950-11ea-8085-8ab55559447e.png)
![image](https://user-images.githubusercontent.com/51064238/70377542-aa180380-1950-11ea-9fbd-17dc87680947.png)

When I zoom in, the orbit is blocked by the earth
-
![image](https://user-images.githubusercontent.com/51064238/70377547-bbf9a680-1950-11ea-9bc7-48056d34dc12.png)

Now I only have RSS in my game, no other mods.So I can exclude the influence of other mods.Does anyone else have this problem?Or am I the only one with this problem?
-

**Comment by DRVeyl** [comment]
This is not a bug, it is the stock behavior of how KSP displays orbits.  At a certain drawing distance, they switch between a 3D rendering mode that occludes lines, and a 2D mode that does not.

**Comment by yixiangop** [comment]
I understand. Thank you very much~!
