### ISSUE TITLE
RSSVE Mod is MISSING!!!!

### ISSUE THREAD

**Issue by Brayaown** [KSP-RO/RealSolarSystem#179]
I know This isn't an Issue about your mod, but I am trying to get ANYONE's attention about this. I am trying to install a graphics mod for Realism Overhaul. Yeah. I am trying to install RSSVE along with Scatterer, and EVE, etc, for your RSS mod. However, the github page for RSSVE is missing!!!!!!! Every other mod is there, but it's like PhineasFreak (or someone else) wiped it off the face of Github. It Doesn't exist! where is it??? It used to be here not long ago according to MANY forums.

This is the page I am installing The mods from : https://github.com/KSP-RO/RP-0/wiki/RSSVE-Installation-Instructions 
THIS is what I see on the github RSSVE mod page: https://github.com/PhineasFreak/RSSVE/tags 

Did he move the mod page??? I can't find it anywhere on google. PS this is for ksp 1.7.3

**Comment by siimav** [comment]
RSSVE is now located here: https://github.com/KSP-RO/RSSVE
