### ISSUE TITLE
planet Ceres is causing me to not be able to play KSP

### ISSUE THREAD

**Issue by Static25** [KSP-RO/RealSolarSystem#187]
whenever i start KSP everything loads and looks normal. when its done loading it switches to a black loading screen with the orbiting planets loading sign. cursor is still there.
i looked into every log i could find and there was only one error repeating itself a few times times. (hundreds in KSP.log)

here's what its said in KSP.log:
--------------------------------
[EXC 14:38:18.273] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <0882401b48d84227ad9c2bbcf4ce8401>:0)

here's what it said in Ceres.body.log:
---------------------------------------
[LOG 14:36:16]: Exception Was Recorded: Object reference not set to an instance of an object

here's what it said in Kopernicus.log:
---------------------------------------
[LOG 14:36:16]: [Kopernicus]: Configuration.Loader: Failed to load Body: Ceres: Object reference not set to an instance of an object

----------------------------------------
something is clearly wrong with Ceres.
here's what i already tried:

completely reinstalling KSP 1.8.1
completely reinstalling RSS.
completely reinstalling all the dependencies.
deleting all my visual mods.
reconfigure both of my GPU's to make sure Unity isn't having problems with my display

what should i do??
any help is appreciated!

**Comment by siimav** [comment]
Try downloading the textures from this link: https://github.com/RCrockford/RSS-Textures/tree/texture-reconvert

**Comment by Static25** [comment]
> 
> 
> Try downloading the textures from this link: https://github.com/RCrockford/RSS-Textures/tree/texture-reconvert

Thank you!
but it still doesn't work.

**Comment by Static25** [comment]
when i delete Ceres, it has a problem with Jupiter.

KSP.log:
[LOG 09:17:47]: Exception Was Recorded: The Biome Map cannot be null if you want to add biomes.

**Comment by siimav** [comment]
Your RSS version?

**Comment by Static25** [comment]
> 
> 
> Your RSS version?

v18.0 recompile for KSP 1.8.1

**Comment by Disoculated** [comment]
I'm also getting the same error usingRSS v18.0 with Kopernicus-1.8.1-1.  on KSP 1.8.1.  Result is an endless loop of "[EXC 18:14:01.329] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <0882401b48d84227ad9c2bbcf4ce8401>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object):"

This is what I think are the relevant parts of my ksp.log (KSP on Windows, if that matters):

[LOG 18:13:45.568] [Kopernicus] Running Kopernicus 1.8.1-1 on KSP 1.8.1
[LOG 18:13:45.576] [Kopernicus] Default logger initialized as Kopernicus
[LOG 18:13:45.580] [Kopernicus] ShaderLoader: Loading asset bundle at path C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program RSS/KSP_x64_Data/../GameData/Kopernicus/Shaders\kopernicusshaders-windows.unity3d
[LOG 18:13:45.581] [Kopernicus] ShaderLoader: adding Kopernicus/Rings
[LOG 18:13:45.732] [Kopernicus]: texture does not exist! C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program RSS/KSP_x64_Data/../GameData/RSS-Textures/PluginData/CeresBiomes.DDS
[LOG 18:13:45.749] [Kopernicus] CalculateArrayLengthOffset using offset of -8
[LOG 18:13:45.749] [Kopernicus] LoadRestOfReader reallocating buffer to 4194304
[WRN 18:13:45.758] DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
[LOG 18:13:45.799] [OD] Adding for body Ceres map named CeresColor (G) for Ceres of path = RSS-Textures/PluginData/CeresColor.dds
[LOG 18:13:46.249] [OD] --> OnDemandStorage.EnableBody loading Ceres
[LOG 18:13:46.297] [OD] ---> Map CeresColor (G) for Ceres enabling self. Path = RSS-Textures/PluginData/CeresColor.dds
[WRN 18:13:46.307] Cannot find preset 'High' for pqs 'Ceres(Clone)'
[LOG 18:13:46.308] lcScatterList
[WRN 18:13:46.309] CelestialBodyTransform: Cannot find CelestialBody.
[EXC 18:13:46.315] Exception: Failed to load Body: Ceres
	Kopernicus.Configuration.Loader.Kopernicus.ConfigParser.Interfaces.IParserEventSubscriber.PostApply (ConfigNode node) (at <0882401b48d84227ad9c2bbcf4ce8401>:0)
	Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, ConfigNode node, System.String configName, System.Boolean getChildren) (at <698cce273aaa41f09ce80d0801f868a2>:0)
	Kopernicus.ConfigParser.Parser.CreateObjectFromConfigNode[T] (ConfigNode node, System.String configName, System.Boolean getChildren) (at <698cce273aaa41f09ce80d0801f868a2>:0)
	Kopernicus.Injector.Awake () (at <0882401b48d84227ad9c2bbcf4ce8401>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	Kopernicus.Injector:Awake()
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	AddonLoader:OnLevelLoaded(GameScenes)
	AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
	UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)
[WRN 18:13:46.322] DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
[LOG 18:13:46.324] [AddonLoader]: Instantiating addon 'AtmosphereFixer' from assembly 'Kopernicus'
[LOG 18:13:46.325] [AddonLoader]: Instantiating addon 'CameraFixer' from assembly 'KSCSwitcher'
[LOG 18:13:46.326] [AddonLoader]: Instantiating addon 'TimeWarpFixer' from assembly 'RealSolarSystem'
[LOG 18:13:46.326] [AddonLoader]: Instantiating addon 'RTDebugUnit' from assembly 'RemoteTech'
[LOG 18:13:46.328] [AddonLoader]: Instantiating addon 'TRActivator' from assembly 'TextureReplacer'
[ERR 18:13:46.869] [Agent]: Is missing its 'title' value

[LOG 18:13:46.879] [Agent]: Found 19 agent mentality types
[ERR 18:13:46.880] [Agent]: Cannot load mentality of name 'Cooperative'. Agent already has a mentality of that type.

[ERR 18:13:46.880] [Agent]: Is missing its 'title' value

[LOG 18:13:46.883] [AgentList]: 32 agents parsed and loaded.
[LOG 18:13:46.963] [UIMasterController]: HideUI
[ERR 18:13:46.987] [PQS]: PQS Ceres(Clone) already marked as started during Start() method. This is probably wrong!

[WRN 18:13:46.989] [PQSCity]: Randolith is not parented to a valid CelestialBody.
[LOG 18:13:46.991] [TR.TRActivator] Started, Version 4.1.3.1559
[LOG 18:13:47.287] [CelestialBody]: Kerbin's solar day length is 6h, 0m, 0s long. sidereal day length is 5h, 59m, 9s long
[LOG 18:13:52.759] [UIMasterController]: HideUI
[LOG 18:13:52.764] [HighLogic]: =========================== Scene Change : From LOADING to MAINMENU =====================

**Comment by Static25** [comment]
@Disoculated 

I fixed the whole thing by reinstalling ksp, and then using CKAN to install RSS, I made a backup of all the other mods I had so I didn't lose them, but it worked! I highly reccomend using CKAN for RSS.
Because, yes its a Bword to install manually.
