### ISSUE TITLE
1.8.1 Textures

### ISSUE THREAD

**Issue by Its-Just-Luci** [KSP-RO/RealSolarSystem#188]
I was wondering if the dev team had any intention of updating the rss textures to be more accurate/higher resolution now that ksp has the shaders and engine to easily handle it?

**Comment by siimav** [comment]
Work in progress in #189 and #192

**Comment by Its-Just-Luci** [comment]
another somewhat related question: is there any plan to add ground-scatters/ breaking ground boulders to analyse on rockier bodies like the moon, mars or mercury?

**Comment by Katniss218** [comment]
> another somewhat related question: is there any plan to add ground-scatters/ breaking ground boulders to analyse on rockier bodies like the moon, mars or mercury?

That would be cool to have. Scatters are good in general, but have to look appropriate (mesh & textures)

**Comment by siimav** [comment]
We have accurate heightmaps for Earth, the Moon and Mars now in addition to fancy shaders for all the bodies.
