### ISSUE TITLE
Launch Sites appears in the pit

### ISSUE THREAD

**Issue by zettich** [KSP-RO/RealSolarSystem#206]
Hey guys,

I'm using a recent RSS from the master branch with a recent RSS 8k textures.
I'm trying to use various launch sites but all of these appear in a pit (see screenshots). When I'm zooming out this, I see the ocean in this place in the low res texture, but it's missing on the hi-res texture. It seems that the earth's texture or the heightmap is shifted.

It seems that my earth is flat and a ground level is 8621 meters on all planet. I fly all earth and it's really flat you know...

![ls3](https://user-images.githubusercontent.com/1737138/86495907-d3ccc800-bd83-11ea-99cc-13baaf1e64b4.jpg)
![ls2](https://user-images.githubusercontent.com/1737138/86495911-d4fdf500-bd83-11ea-915d-02fa4cd61aec.jpg)
![ls1](https://user-images.githubusercontent.com/1737138/86495913-d5968b80-bd83-11ea-8814-77fac8e3854a.jpg)

**Comment by siimav** [comment]
With the RSS master you will need to download textures from here: https://github.com/KSP-RO/RSS-Textures/releases/tag/v18.2
