### ISSUE TITLE
Northern polar ice cap completly melted with v18.1.2 for KSP 1.8.1

### ISSUE THREAD

**Issue by Myshiko** [KSP-RO/RealSolarSystem#209]
In RSS v18.1.2 for KSP 1.8.1 global warming completely melted away Earth northern Polar Cap (haven't checked South). So, now it's liquid water and barren land (biomes register as water and ice caps).

From the orbit / map view the Earth polar ice is rendered fine. But flying low looks like water and landing is water and splash (not solid ice).

On RSS v.18.1.0 ice worked correctly.

**Comment by siimav** [comment]
This one's for you, @RCrockford

**Comment by RCrockford** [comment]
This is fixed in RSS-Textures v18.5.
