### ISSUE TITLE
Venus atmosphere pressure is wrong in the info window

### ISSUE THREAD

**Issue by peninha** [KSP-RO/RealSolarSystem#219]
![screenshot15](https://user-images.githubusercontent.com/1134185/91712377-00237b80-eb5e-11ea-8c8d-6a66d7afdfba.png)
It's showing Mars atmosphere pressure.

**Comment by siimav** [comment]
Fixed in 3bc6f24ffda127f8ba051d3d2d92932ba62b71a7
