### ISSUE TITLE
main forum page for this mod needs to be updated to indicate 1.7.3

### ISSUE THREAD

**Issue by ezeeetm** [KSP-RO/RealSolarSystem#223]
https://forum.kerbalspaceprogram.com/index.php?/topic/177216-173-real-solar-system-v164-26-nov-2019/

First post currently says

> Manual installation:
> 1. Download Kerbal Space Program 1.6.1 and create a fresh install on your hard drive.

Needs to be updated to say 1.7.3 I think?

**Comment by siimav** [comment]
@Theysen the links on the forum page point to specific versions. Maybe just make them point to the releases page since we probably can't manage to keep the forum thread up to date.
