### ISSUE TITLE
Add a CommNet station for NZ - Mahia

### ISSUE THREAD

**Issue by kaezone** [KSP-RO/RealSolarSystem#224]
At the moment it isn't possible to transmit telemetry or anything when launching from the NZ - Mahia pad, as there's no CommNet station configured, only a RemoteTech ground station. Is anybody opposed to adding a CommNet station there?

**Comment by leudaimon** [comment]
If this was not done yet, please feel free to add it. Most likely when Mahia was added no one was using CommNet and it was forgotten.

**Comment by siimav** [comment]
@RCrockford since you're playing your current career from Mahia, is this still an issue?

**Comment by RCrockford** [comment]
This is still an issue, I added one for myself locally to resolve it.
I will push that as a PR.
