### ISSUE TITLE
Update RSSVE link on forum post

### ISSUE THREAD

**Issue by kyleander** [KSP-RO/RealSolarSystem#231]
on the forum post, it links to RSSVE by Phineas Freak. this is fine, except that github.com/PhineasFreak/RSSVE no longer exists, so people may be confused because the mod is gone. Perhaps you could update the link to the new RSSVE repo?

**Comment by siimav** [comment]
This one's for you, @Theysen

**Comment by Theysen** [comment]
on it, will make a spring clean for all threads I maintain. Thanks for the headsup - honestly thought the forums are dead.

**Comment by kyleander** [comment]
Thanks!
