### ISSUE TITLE
Game crashes when entering phobos orbit

### ISSUE THREAD

**Issue by dennislee9999** [KSP-RO/RealSolarSystem#237]
When I enter phobos orbit, the game freezes and crash.
I will add my ksp log file via google drive.
https://drive.google.com/file/d/1vIqrBuEmtFlDCTcvr4Bw23P2A38ye1CE/view?usp=sharing

**Comment by siimav** [comment]
Sorry but the log doesn't contain any relevant information that would point to the cause of the crash, or whether it's even related to RSS. We can't do anything unless the crash can be replicated by following some specific steps.
