### ISSUE TITLE
Asteroid CTD bug

### ISSUE THREAD

**Issue by 1fabrism** [KSP-RO/RealSolarSystem#238]
Hello, I recently started a career game with a bunch of mods (RSS, principia, ...) . All was good until I embarked on an asteroid intercept mission: just moments before grabbing the G-class asteroid with the claw, the game crashes. This happens every time.

I started uninstalling my mods one at a time and the only one i found to have an effect was Principia: after removing its folder from GameData the game no longer crashed when about to hit the asteroid, but instead when the ship finally touched it it disappeared inside. Zooming in until the camera was within the surface of the asteroid there was no ship to be found, yet I could tell it still existed (throttle, SAS, etc. still worked and I could hear the engine). 

I am attaching KSP.log and player.log, let me know if you need any other information. Game version 1.11.1
[KSP.log](https://github.com/KSP-RO/RealSolarSystem/files/6422745/KSP.log)
[Player.log](https://github.com/KSP-RO/RealSolarSystem/files/6422746/Player.log)

![Untitled](https://user-images.githubusercontent.com/21246117/117044014-35e0bb80-ad0e-11eb-83a4-7b00f9845193.jpg)

**Comment by siimav** [comment]
Sounds like you have 2 separate issues there? If Principia is responsible for the crash then you should follow [these](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs) instructions on how to report it to the Principia devs.

**Comment by 1fabrism** [comment]
Yea could be, i really don't know much about this stuff. My theory was that something went wrong with the dimensions or texture of the asteroid, principia found out somehow and crashed the game for good measure. So without principia the bug persists but it doesn't crash anymore?
Anyway i'll open an issue with them as well.

EDIT: do you need the logs of the bug without Principia then?

**Comment by DRVeyl** [comment]
Closing here since the issue has migrated to Principia.
