### ISSUE TITLE
Need to add a SolarPowerCurve scaled for RSS

### ISSUE THREAD

**Issue by NoPanShabuShabu** [KSP-RO/RealSolarSystem#24]
The SolarPowerCurve section in RSSKopernicus.cfg appears to be a place holder with some rudimentary values scaled to Kerbol system.

**Comment by NathanKell** [comment]
Afaik it's not used in ksp 1.0

Sent by my thumbs, slowly.

**Comment by NoPanShabuShabu** [comment]
Well, that doesn't seem to be the case.  I had already replaced the power curve with one of my own devising on my real game, but just to be absolutely certain, here's a test using pure stock KSP with RSS only (and of course latest Kopernicus, 2k textures).

OX-4L 1x6 solar panels, which should produce 1.6 /s:

147 Gm: 0.34 /s
150 Gm: 0.31 /s
160 Gm: 0.22 /s
170 Gm: 0.14 /s
180 Gm: 0.08 /s
190 Gm: 0.03 /s
200 Gm: 0.00 /s

Replaced with my curve I get:
200 Gm: 0.91 /s
210 Gm: 0.82 /s
220 Gm: 0.74 /s
230 Gm: 0.68 /s
240 Gm: 0.63 /s
250 Gm: 0.59 /s

Which are pretty close to what I should theoretically get (with the power at 1 AU being 1x.)

**Comment by NathanKell** [comment]
@ThomasKerman can I safely delete the node entirely, or will starlight switcher need something? I'd like to use the stock functionality where solar power curves are ignored entirely.

**Comment by StollD** [comment]
No, simply delete it. The switcher will ignore it. (Works already for stock Sun in System.cfg) :]

**Comment by NoPanShabuShabu** [comment]
OK, tested removing the SolarPowerCurve node (commented out.)  
With the standard Kopernicus, I got 0 power no matter where.  With the Starlight hotfix for Kopernicus, I get power consistent with what it should be, about 1x at 1 AU, about .25x at 2 AU.  Edit: actually reading a little bit high, but not far off.

So, it looks it will need that hotfix to work.
