### ISSUE TITLE
Game stuck on loading screen

### ISSUE THREAD

**Issue by ILoveMoarBoosters** [KSP-RO/RealSolarSystem#246]
The game never gets past the loading screen for some reason... the last time i played in RO/RSS was last month and the game loaded just fine and since the past week the game never gets past the loading screen and i installed the avc mod to see what was wrong and even it couldn't load or give any debug 

my computer:
i5 8th gen
gtx 710
8gb ram

how i play:
got ksp on steam
install all mods through ckan

didn't use these suggested mods:
persistent rotation
ksc switcher

texture config: 2048x1024

please fix this issue as i am unable to play with this mod.

**Comment by siimav** [comment]
Not the fault of RSS if it worked last month and now it no longer does without you making any changes to your install. Did you already try loading your install multiple times to rule some transient issue? If yes, I would suggest trying a fresh install, including redownloading KSP again.
