### ISSUE TITLE
Add tracking station downrange of Baikonur

### ISSUE THREAD

**Issue by sohmien** [KSP-RO/RealSolarSystem#247]
There is a tracking station downrange of Cape Canaveral (Bermuda), but no tracking station downrange of Baikonur.
Historically there was a tracking station called Sary Shagan or Balkhash Radar Station at 46°00′04.65″N 73°38′52.11″E.
Let's not discriminate against the Soviet player and add this tracking station :)

**Comment by Capkirk123** [comment]
Should be resolved by https://github.com/KSP-RO/RealAntennas/pull/11

**Comment by Capkirk123** [comment]
Actually already resolved in https://github.com/KSP-RO/RealSolarSystem/pull/295. This doesn't add NIP-3 at Sary Shagan, but it does add NIP-4 and NIP-6, which should ensure a constant connection over the USSR for launches to ~60 degrees.
