### ISSUE TITLE
Pluto/Mercury refered to as "the Pluto" and "the Mercury"

### ISSUE THREAD

**Issue by jrossignol** [KSP-RO/RealSolarSystem#25]
Noticed this while play-testing some of my contracts on RSS - any of the bodies that are based on Mun show up in text as "the Pluto" instead of "Pluto" (because CelestialBody.use_The_InName is set to true.

I looked at the Kopernicus documentation, and they don't have a published setting, but it looks like it is supported by setting the useTheInName flag in their config (see [here](https://github.com/BryceSchroeder/Kopernicus/blob/c8bdec03c12a2bef9856d9c5a14e259a45db47ca/Kopernicus/Configuration/Properties.cs#L218)).

**Comment by NathanKell** [comment]
Hah! Nice catch. Can't believe we missed that one. <blush>

**Comment by NoPanShabuShabu** [comment]
For this to work you need to put the "useTheInName" line in Properties{}, not Body{}.

Also, I pointed this issue (though not the solution) out weeks ago on the forum. ;)

**Comment by NathanKell** [comment]
...whoops. Double whoops.
