### ISSUE TITLE
Main Menu Not Loading

### ISSUE THREAD

**Issue by NightFlyer0012** [KSP-RO/RealSolarSystem#258]
After the game loads all of the plugins, parts, and expansions, I get stuck where the main menu would normally be. I can hear the music but all I have is the loading animation in the lower right corner of the screen. I am on a fresh install of KSP 1.12.3 with only RSS and its dependencies.
![20220426162304_1](https://user-images.githubusercontent.com/104468712/165403482-34b511cf-ba96-42d1-bdfb-341b2e2ec9ba.jpg)
 
Please let me know if you need any more info.

**Comment by siimav** [comment]
Start with uploading ksp.log

**Comment by NightFlyer0012** [comment]
[KSP.log](https://github.com/KSP-RO/RealSolarSystem/files/8586998/KSP.log)

Here is my log.

**Comment by siimav** [comment]
Looks like you tried installing mods manually and you definitely made mistakes along the way (as implied by having a folder called  `CustomBarnKit-master` in your gamedata. I would strongly suggest starting from scratch and using CKAN to install mods.

**Comment by NightFlyer0012** [comment]
Alright I will give that a go thanks!
