### ISSUE TITLE
Triton's spaceAltitudeThreshold lower than atmosphere

### ISSUE THREAD

**Issue by Mirviy** [KSP-RO/RealSolarSystem#261]
So it is impossible to do science in Triton's low space.

Triton.cfg:
ScienceValues{
...
    spaceAltitudeThreshold = 80000  # I suggest this should be 800000

and
Atmosphere{
    maxAltitude = 110000.0

**Comment by Mirviy** [comment]
Pluto too.

**Comment by Capkirk123** [comment]
resolved in https://github.com/KSP-RO/RealSolarSystem/commit/2b9f5e45db0a739b91adab2ed83df2b8dc233da7 and https://github.com/KSP-RO/RealSolarSystem/commit/b498e173d40a9bbc597b118a15711f5b0b430071
