### ISSUE TITLE
Korean launch sites do not have tracking stations

### ISSUE THREAD

**Issue by ghost** [KSP-RO/RealSolarSystem#265]
In LaunchSites.cfg there are two sites in Korea: Sohae (North Korea) and Naro (South Korea). Both of them lack tracking stations and are therefore unplayable. Suggest to add tracking stations in RSS_CommNet_Stations.cfg.

**Comment by ghost** [comment]
Pull request #266

**Comment by siimav** [comment]
Looks like @leudaimon already took care of this a while ago.
