### ISSUE TITLE
Rings or moons of Uranus are wrong inclination with Principia

### ISSUE THREAD

**Issue by hallucinogender** [KSP-RO/RealSolarSystem#267]
With Principia, either the rings or the moons of Uranus are at the wrong inclination. I'm not sure which is wrong (or if both are wrong, which is a possibility) but at least one of them does need fixing. Linked image demonstrates the error.
https://i.imgur.com/ziwAG0y.png

**Comment by lpgagnon** [comment]
pretty sure RSS doesn't give Uranus any rings. Are you using katniss stuff? see https://github.com/KSP-RO/RealSolarSystem/pull/220

**Comment by hallucinogender** [comment]
I have RSSVE installed, I'll check if it's that which adds the rings.

**Comment by hallucinogender** [comment]
Edit: It's not RSSVE. I have no idea what's adding the rings. It'll be something in the RP-1 express install but I don't know what it could be.

**Comment by siimav** [comment]
Lpg is correct. Express install definitely doesn't come with rings. You must've installed Katnisss'sss stuff or some other visual mod.
