### ISSUE TITLE
Incompatibles with Parallax 2.x

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [KSP-RO/RealSolarSystem#273]
The newest Parallax 2.0.x has been released, and the current config can not be parsed correctly. I got an exception like this:
`Exception Was Recorded: Missing non-optional field: ParallaxOptimized.Subdivide.subdivisionRadius`

sorry for not sending the complete error log, I have added the subdivsionRadius to the config and this exception is gone now, but I still can not get the Parallax effect working with RSS now.

**Comment by siimav** [comment]
Parallax 2.x isn't compatible yet. Use 1.3.1.
