### ISSUE TITLE
RSS isn't detected

### ISSUE THREAD

**Issue by Maister343** [KSP-RO/RealSolarSystem#277]
Hello.
I've wanted to play with RSS only on version 1.10 but when I launch the game there is a notification in the menu that RSSVE requires Real Solar System to work but I have RSS downloaded and I don't know how to repair it. For easier understanding of my problem I've attached a screenshot 

![Zrzut ekranu (165)](https://user-images.githubusercontent.com/117588680/200182645-efea9833-1f47-4783-8c33-f937e341dc9f.png)

**Comment by siimav** [comment]
Use KSP 1.12 and then install RSS through CKAN.

**Comment by Maister343** [comment]
I was playing on 1.12 but it still wasn't working. But I finally managed to make RSS work on 1.10
