### ISSUE TITLE
Phobos SOI too small

### ISSUE THREAD

**Issue by Losalex42** [KSP-RO/RealSolarSystem#287]
SOI is the same as the radius. Makes it impossible to orbit or land on.

20.0.0 KSP 1.12.3

**Comment by siimav** [comment]
That certainly isn't the case on my install.
![image](https://github.com/KSP-RO/RealSolarSystem/assets/1120038/0e347511-c4ac-47ef-b4f6-f182ea87d015)

**Comment by Losalex42** [comment]
![Kerbal Space Program Screenshot 2023 06 21 - 15 06 21 67](https://github.com/KSP-RO/RealSolarSystem/assets/100455940/22777e15-a694-488a-b434-fb3f1e6a2dcf)
Very strange.

**Comment by siimav** [comment]
I'm going to bet that this is a conflict with some other mod and not actually an issue with RSS itself.

**Comment by Losalex42** [comment]
I've whiped my ksp folder and reinstalled everything and using the bare minimum to get rss working. It's still an issue. I did use CKAN though.

**Comment by Losalex42** [comment]
I downgraded to rss v19.1.0 from 20.0.0 and that fixed the issue.

**Comment by siimav** [comment]
Ahh, so turns out that the install I had open at that time was running RSS v19.1. Can confirm that the issue started happening in v20 so it has to be related to #285.

Not sure why setting `finalizeOrbit` to `false` caused other side effects rather than just the orbital period changes. Maybe @R-T-B has ideas?

**Comment by gotmachine** [comment]
From [one of my comments on the issue](https://github.com/Kopernicus/Kopernicus/issues/584#issue-1680020968) : 

> I'm not entirely sure why the FinalizeOrbit() method is also recomputing the hill sphere and SOI, this seems like something that should be independent of the period / meanMotion hack, so in case setting finalizeOrbit = true also has this purpose, I would suggest gating the hack behind an additional config switch so planets configs can opt-out of it.
