### ISSUE TITLE
RSS does not overwrite the stock Mechjeb Runway definitions?

### ISSUE THREAD

**Issue by Willt125** [KSP-RO/RealSolarSystem#303]
As far as I can tell, Mechjeb is still using the stock location of the KSC, instead of having the RSS sites.

![screenshot11](https://github.com/user-attachments/assets/15ff719b-818a-4533-8cc1-bd4f9b09748a)

**Comment by Capkirk123** [comment]
The MechJeb Aircraft Autopilot is broken and unmaintained. There's not any point in fixing runway locations while this is still true.
