### ISSUE TITLE
Titan low-space threshold within atmosphere

### ISSUE THREAD

**Issue by danielguo** [KSP-RO/RealSolarSystem#41]
Hi, Titan has Atmosphere.maxAltitude = 600km, but ScienceValues.spaceAltitudeThreshold = 500km. Therefore, it is not possible to get in-space-low science experiments running for Titan.

**Comment by PhineasFreak** [comment]
This has been fixed by @pap1723 in PR https://github.com/KSP-RO/RealSolarSystem/commit/127211ec703af19a01d58c38fb15de65453dd784. The new space altitude threshold is now **750 km**.
