### ISSUE TITLE
SS FAR/NEAR clipping plane values won't load from config

### ISSUE THREAD

**Issue by Pingopete** [KSP-RO/RealSolarSystem#47]
Might be a config error on my end but I think I have it written out right.

**Comment by NathanKell** [comment]
Ok. I will look into this when I have a sec!

**Comment by Pingopete** [comment]
Thanks

**Comment by PhineasFreak** [comment]
Just to put a closure to this issue. Here is a list of the available RSS camera names:

* cam00FarClip
* cam00NearClip
* cam01FarClip
* cam01NearClip
* camScaledSpaceFarClip
* camScaledSpaceNearClip

I am currently using the **camScaledSpaceNearClip** to minimize the effects of Z-fighting on the gas giants and i can verify that it works as expected.
